name: CI

on:
  workflow_dispatch:
    inputs:
      chosen_environment:
        type: choice
        description: Choose an environment
        required: false
        default: 'dev'
        options: 
        - dev
        - test
        - preprod
        - prod

env:
  ENVIRONMENT_NAME: ${{ github.event.inputs.chosen_environment }}

jobs:
  chosen:
    runs-on: ubuntu-latest

    if: ${{ env.ENVIRONMENT_NAME == 'dev' }}
      environment: dev
    
    if: ${{ env.ENVIRONMENT_NAME == 'test' }}
      environment: test


    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo ${{ env.ENVIRONMENT_NAME }}
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
  
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo ${{ env.ENVIRONMENT_NAME }}
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
  
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo ${{ env.ENVIRONMENT_NAME }}
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
