name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose an environment
        required: false
        default: 'dev'
        options: 
        - dev
        - test
        - preprod
        - prod

env:
  ENVIRONMENT_NAME: ${{ github.event.inputs.environment }} 

jobs:
  chosen:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo "Environment is: ${{ env.ENVIRONMENT_NAME }}"
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
  
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo "Environment is: ${{ env.ENVIRONMENT_NAME }}"
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
  
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo ${{ secrets.BENT }}

      - name: Run a multi-line script
        run: |
          echo "Environment is: ${{ env.ENVIRONMENT_NAME }}"
          echo "Dev secret is Burg: Is it working: ${{ secrets.BENT == 'Burg' }}"
          echo "Test secret is Faber: Is it working: ${{ secrets.BENT == 'Faber' }}"
